# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2021-05-17 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('cliente_id', models.PositiveIntegerField(default=1)),
                ('ip_visited', models.CharField(blank=True, max_length=200)),
                ('download', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
